import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Free Etsy SEO Checker — Terms of Use | TheSellerMind",
  description:
    "Terms of use for the SellerMind Free Etsy SEO Checker bookmarklet. Plain English, no dark patterns.",
  alternates: { canonical: "https://thesellermind.com/legal/etsy-seo-checker-terms" },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "June 30, 2026";

export default function EtsySeoCheckerTermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-10 md:py-16">
      <nav className="text-xs text-stone-500">
        <Link href="/" className="hover:underline">Home</Link>
        <span className="mx-2">/</span>
        <Link href="/free-etsy-seo-checker" className="hover:underline">
          Free Etsy SEO Checker
        </Link>
        <span className="mx-2">/</span>
        <span className="text-stone-700">Terms of Use</span>
      </nav>

      <header className="mt-6">
        <h1 className="text-3xl font-bold text-stone-900 md:text-4xl">
          Free Etsy SEO Checker — Terms of Use
        </h1>
        <p className="mt-3 text-sm text-stone-500">
          Last updated: {LAST_UPDATED} · Plain-English version. By installing or using
          the SellerMind Etsy SEO Checker bookmarklet you agree to the terms below.
        </p>
      </header>

      <section className="prose prose-stone mt-8 max-w-none text-stone-700">
        <h2 className="text-xl font-semibold text-stone-900">1. What this tool does</h2>
        <p>
          The SellerMind Free Etsy SEO Checker is a one-click bookmarklet. When you
          activate it on a public Etsy listing page, it reads listing data already
          visible in <em>your own browser</em> (title, public description, tags, image
          alt text and counts) and sends a compact summary to our backend. Our
          backend runs an AI scoring pass and returns a 0–100 SEO score plus
          improvement suggestions. The whole flow takes a few seconds.
        </p>

        <h2 className="text-xl font-semibold text-stone-900">2. What you agree to</h2>
        <ul>
          <li>
            <strong>Use it on listings you are authorised to analyse.</strong>{" "}
            Typically that means your own shop. You may also analyse public
            competitor listings for research, but you may not use this tool to
            harass sellers, copy listings, or take any action that violates Etsy&apos;s
            own Terms of Use.
          </li>
          <li>
            <strong>You will not abuse the service.</strong> The tool is rate-limited
            to a small number of audits per IP per day. Trying to bypass the limits,
            scrape the API, or use the tool for automated mass scoring is prohibited
            and will result in your IP being blocked.
          </li>
          <li>
            <strong>The bookmarklet runs in your browser, on your behalf.</strong>{" "}
            It does not log you in, does not touch private Etsy data behind your
            seller account, and does not make any requests to Etsy&apos;s backend on
            our servers.
          </li>
        </ul>

        <h2 className="text-xl font-semibold text-stone-900">3. What we do with the data</h2>
        <ul>
          <li>
            <strong>No raw listing content is persisted on our servers.</strong> The
            title / tags / description / image alt text you send us are passed to the
            AI model in memory and discarded once the audit completes. We do not
            write them to a database, log them in plain text, or share them.
          </li>
          <li>
            <strong>Anonymous telemetry only.</strong> We log non-PII metrics
            (HTTP status, parse quality flag, total score bucket, latency, listing
            ID number) to monitor cost and reliability. No email is collected, no
            cookies are dropped by the tool itself.
          </li>
          <li>
            <strong>You can opt out by not using the tool.</strong> No account, no
            sign-up form, no tracking pixel.
          </li>
        </ul>

        <h2 className="text-xl font-semibold text-stone-900">4. AI output disclaimer</h2>
        <p>
          The score and suggestions are generated by a large language model
          following our published{" "}
          <Link href="/free-etsy-seo-checker/methodology" className="text-[#E07A5F] hover:underline">
            scoring rubric
          </Link>
          . AI output is directional and can be wrong. We do not guarantee any
          ranking, traffic, or sales outcome. Treat the score as a starting
          conversation, not a verdict. You remain solely responsible for any
          changes you make to your listings.
        </p>

        <h2 className="text-xl font-semibold text-stone-900">5. Relationship with Etsy</h2>
        <p>
          SellerMind is an independent indie product. We are not affiliated with,
          endorsed by, or sponsored by Etsy, Inc. &quot;Etsy&quot; is a trademark of
          Etsy, Inc.; we reference it strictly for descriptive purposes. If Etsy
          changes its public page layout, the bookmarklet may temporarily fail and
          we will update it on a best-effort basis.
        </p>

        <h2 className="text-xl font-semibold text-stone-900">6. Service can change or stop</h2>
        <p>
          This is a free tool we run at our own cost. We may modify, rate-limit, or
          discontinue it at any time, with or without notice. Continued use after
          changes means you accept the updated terms.
        </p>

        <h2 className="text-xl font-semibold text-stone-900">7. Liability</h2>
        <p>
          The tool is provided &quot;as is&quot;, without warranty of any kind. To the
          maximum extent permitted by law, SellerMind&apos;s total liability for any
          claim relating to your use of this free tool is capped at USD $0.00 — i.e.,
          what you paid for it.
        </p>

        <h2 className="text-xl font-semibold text-stone-900">8. Contact</h2>
        <p>
          Questions, or noticed a problem? Email{" "}
          <a href="mailto:hello@thesellermind.com" className="text-[#E07A5F] hover:underline">
            hello@thesellermind.com
          </a>{" "}
          and we&apos;ll get back to you. See also our{" "}
          <Link href="/privacy" className="text-[#E07A5F] hover:underline">
            Privacy Policy
          </Link>{" "}
          and{" "}
          <Link href="/terms" className="text-[#E07A5F] hover:underline">
            site-wide Terms
          </Link>
          .
        </p>

        <p className="mt-10 text-xs text-stone-500">
          This page is plain English on purpose. We don&apos;t use scary lawyer
          language because we don&apos;t have anything to hide. If you&apos;re a lawyer
          and you think we should, please tell us at the address above.
        </p>
      </section>
    </main>
  );
}
