import type { Metadata } from "next";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata: Metadata = {
  title: "Terms of Service | SellerMind",
  description: "Terms of service for SellerMind - Read our terms governing the use of our AI-powered Etsy seller tools.",
  alternates: {
    canonical: "https://thesellermind.com/terms",
  },
  openGraph: {
    title: "Terms of Service | SellerMind",
    description: "Terms of service for SellerMind - Read our terms governing the use of our AI-powered tools.",
    url: "https://thesellermind.com/terms",
    type: "website",
  },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-4xl space-y-8">
      <div className="text-center">
        <h1 className="text-3xl font-bold text-foreground-primary sm:text-4xl">
          Terms of Service
        </h1>
        <p className="mt-2 text-foreground-secondary">
          Last updated: June 2026
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Agreement to Terms</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            By accessing or using SellerMind (&quot;the Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service.
          </p>
          <p className="mt-4">
            <strong>SellerMind is not affiliated with, endorsed by, or connected to Etsy, Inc.</strong> Etsy is a trademark of Etsy, Inc.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Geographic Restrictions</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p className="font-semibold">
            IMPORTANT: This service is not available to users in certain jurisdictions.
          </p>
          <p className="mt-4">
            <strong>SellerMind does not provide services to individuals or entities located in, or who reside in, mainland China, the Hong Kong Special Administrative Region, the Macau Special Administrative Region, or Taiwan</strong> (collectively, &quot;Restricted Regions&quot;).
          </p>
          <p className="mt-4">
            By using this website and services, you represent and warrant that you are not located in, and do not reside in, any of the Restricted Regions. If we determine that you are accessing our services from a Restricted Region, your access may be blocked or terminated in accordance with applicable laws and regulations.
          </p>
          <p className="mt-4">
            <strong>IP Address Blocking:</strong> Our website may automatically block access from IP addresses associated with the Restricted Regions. We utilize IP geolocation data from hosting providers and content delivery networks to enforce these geographic restrictions.
          </p>
          <p className="mt-4">
            These restrictions are implemented for compliance purposes and do not constitute an admission that any Restricted Region&apos;s laws apply to our activities.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Description of Service</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            SellerMind provides AI-powered tools for Etsy sellers, including but not limited to:
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>Listing Generator - Create SEO-optimized product listings</li>
            <li>Auto Reply - Generate customer service responses</li>
            <li>Holiday Marketing - Create seasonal marketing content</li>
            <li>Review Handler - Generate review responses</li>
            <li>Batch Optimizer - Optimize multiple listings at once</li>
          </ul>
          <p className="mt-4">
            We reserve the right to modify, suspend, or discontinue any part of the Service at any time.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>AI-Generated Content Disclaimer</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p className="font-semibold">
            AI-generated content is for reference only and should not be considered professional advice. Please review and edit before publishing on your shop.
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li><strong>Reference Only:</strong> All content generated by our AI tools is for informational and reference purposes only. It is not professional advice and does not constitute a substitute for professional judgment.</li>
            <li><strong>Review Required:</strong> You are responsible for reviewing and editing all generated content before use. SellerMind strongly recommends that you carefully proofread all AI-generated outputs.</li>
            <li><strong>No Guarantees:</strong> We do not guarantee the accuracy, completeness, relevance, or suitability of AI-generated content for any specific purpose. AI-generated outputs may contain inaccuracies, errors, omissions, or outdated information.</li>
            <li><strong>Independent Verification:</strong> You should independently verify all factual claims, statistics, legal references, and other information in AI-generated content before relying on it or publishing it.</li>
            <li><strong>Etsy Policy Compliance:</strong> You are responsible for ensuring your use of generated content complies with Etsy&apos;s policies, terms of service, and applicable laws.</li>
            <li><strong>Liability Disclaimer:</strong> We are not responsible for any outcomes, losses, or damages resulting from the use of AI-generated content, including but not limited to listing removals, account suspensions, or lost revenue.</li>
          </ul>
          <p className="mt-4">
            <strong>⚠️ This service uses artificial intelligence (DeepSeek) to generate content.</strong> AI-generated outputs may contain inaccuracies. Users should verify all information independently before making any business decisions.
          </p>
          <p className="mt-4">
            The Service is provided &quot;as is&quot; without warranties of any kind, express or implied.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>User Responsibilities</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>By using the Service, you agree to:</p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>Use the Service only for lawful purposes and in accordance with these Terms</li>
            <li>Not use the Service to generate content that violates any law or regulation</li>
            <li>Not use the Service to infringe on any intellectual property rights</li>
            <li>Not attempt to gain unauthorized access to any part of the Service</li>
            <li>Not interfere with or disrupt the Service or servers connected to the Service</li>
            <li>Comply with all applicable Etsy policies and guidelines when using generated content</li>
            <li>Not access the Service if you are located in a Restricted Region (mainland China, Hong Kong, Macau, or Taiwan)</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Intellectual Property</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            The Service and its original content, features, and functionality are owned by SellerMind and are protected by international copyright, trademark, and other intellectual property laws.
          </p>
          <p className="mt-4">
            You retain ownership of any content you input into the Service. You grant us a limited license to use your input solely to provide the Service to you.
          </p>
          <p className="mt-4">
            Generated content may be similar to content used by others. We are not responsible for any intellectual property disputes arising from your use of generated content.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Limitation of Liability</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            To the fullest extent permitted by law:
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>SellerMind shall not be liable for any indirect, incidental, special, consequential, or punitive damages</li>
            <li>SellerMind shall not be liable for any loss of profits, data, goodwill, or other intangible losses</li>
            <li>SellerMind shall not be liable for any outcomes resulting from the use of AI-generated content</li>
            <li>SellerMind shall not be liable for any actions taken by Etsy against your shop</li>
            <li>Our total liability shall not exceed $100 USD</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Indemnification</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            You agree to defend, indemnify, and hold harmless SellerMind, its operators, and any affiliated parties from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees arising out of or relating to your use of the Service or violation of these Terms.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Privacy</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            Your privacy is important to us. Please review our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link> to understand how we collect, use, and protect your information.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Third-Party Links</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            The Service may contain links to third-party websites or services that are not owned or controlled by SellerMind. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Service Availability</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            We strive to keep the Service available at all times, but we do not guarantee uninterrupted access. The Service may be temporarily unavailable due to:
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>Scheduled or emergency maintenance</li>
            <li>Technical issues beyond our control</li>
            <li>Third-party service disruptions</li>
            <li>Force majeure events</li>
            <li>Geographic access restrictions as described above</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Changes to Terms</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            We reserve the right to modify or replace these Terms at any time at our sole discretion. If a revision is material, we will provide at least 30 days&apos; notice prior to any new terms taking effect.
          </p>
          <p className="mt-4">
            Continued use of the Service after any changes constitutes acceptance of the new Terms.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Governing Law</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which SellerMind operates, without regard to its conflict of law provisions.
          </p>
          <p className="mt-4">
            <strong>Note for International Users:</strong> Given that SellerMind does not provide services to users in the Restricted Regions, any disputes arising from use of the Service by persons in the Restricted Regions shall be governed by applicable international laws and the laws of the jurisdiction where SellerMind operates.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Severability</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            If any provision of these Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Entire Agreement</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            These Terms, together with our Privacy Policy, constitute the entire agreement between you and SellerMind regarding the Service and supersede all prior agreements and understandings.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>EU Consumer Rights</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            If you are located in the European Union (EU) or European Economic Area (EEA), you have the following additional consumer rights:
          </p>

          <h3 className="text-base font-semibold text-foreground-primary mt-4">Right of Withdrawal (14 Days)</h3>
          <p>
            Under the EU Consumer Rights Directive 2011/83/EU, EU consumers have the right to withdraw from a distance contract within <strong>14 days</strong> without providing any reason. The withdrawal period expires 14 days after the day on which you enter into the subscription contract.
          </p>
          <p className="mt-4">
            To exercise your right of withdrawal, please notify us at <strong>legal@thesellermind.com</strong> of your decision before the withdrawal period expires. We will reimburse all payments received from you without undue delay and no later than 14 days after we are informed of your decision.
          </p>
          <p className="mt-4">
            <strong>Exception:</strong> This right of withdrawal does not apply to digital content that has been delivered to you with your prior express consent and you acknowledge that you lose this right once the digital content has been delivered and used.
          </p>

          <h3 className="text-base font-semibold text-foreground-primary mt-4">Online Dispute Resolution (ODR)</h3>
          <p>
            In accordance with EU Regulation (EU) No 524/2013 on online dispute resolution (ODR) for consumer disputes, you may use the <strong>EU Online Dispute Resolution (ODR) platform</strong> to resolve disputes out of court at:{' '}
            <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
              https://ec.europa.eu/consumers/odr
            </a>
          </p>
          <p className="mt-4">
            The ODR platform provides a single point of entry for consumers and traders to access high-quality and user-friendly alternative dispute resolution services. However, participation in the ODR platform is voluntary for traders, and SellerMind is not obligated to participate in ODR proceedings.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Refund Policy</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            We want you to be satisfied with SellerMind. Below is our refund policy:
          </p>

          <h3 className="text-base font-semibold text-foreground-primary mt-4">7-Day Money-Back Guarantee</h3>
          <p>
            We offer a <strong>7-day money-back guarantee</strong> for all new subscribers. If you are not satisfied with the Service within the first 7 days of your subscription, you may request a full refund. To request a refund, contact us at <strong>legal@thesellermind.com</strong> within 7 days of your initial subscription date.
          </p>
          <p className="mt-4">
            After the 7-day period, refunds are provided at our sole discretion on a case-by-case basis.
          </p>

          <h3 className="text-base font-semibold text-foreground-primary mt-4">EU Consumer 14-Day Withdrawal Right</h3>
          <p>
            EU and EEA consumers have a statutory <strong>14-day right of withdrawal</strong> under the EU Consumer Rights Directive 2011/83/EU. This right allows EU consumers to cancel their subscription contract within 14 days without penalty. This right is in addition to our voluntary 7-day money-back guarantee.
          </p>
          <p className="mt-4">
            To exercise your EU withdrawal right, contact us at <strong>legal@thesellermind.com</strong>. We will process your refund within 14 days of receiving your withdrawal notice.
          </p>

          <h3 className="text-base font-semibold text-foreground-primary mt-4">Refund Processing</h3>
          <p>
            Approved refunds will be processed using the original payment method. Refunds are typically processed within 5–10 business days, depending on your payment provider.
          </p>
          <p className="mt-4">
            <strong>Non-Refundable Items:</strong> Refunds are not available for: (a) digital content that has been accessed and used; (b) subscriptions that have been active for more than 7 days (except for EU consumer withdrawal rights); (c) services already rendered.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Contact Information</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>If you have any questions about these Terms, please contact us:</p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>Email: legal@thesellermind.com</li>
            <li>Website: https://thesellermind.com</li>
          </ul>
        </CardContent>
      </Card>

      <div className="flex justify-center">
        <Link
          href="/"
          className="text-primary hover:text-primary-hover font-medium"
        >
          ← Back to Home
        </Link>
      </div>
    </div>
  );
}
