import type { Metadata } from "next";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata: Metadata = {
  title: "Terms of Service | SellerMind",
  description: "Terms of service for SellerMind - Read our terms governing the use of our AI-powered Etsy seller tools.",
  alternates: {
    canonical: "https://thesellermind.com/terms",
  },
  openGraph: {
    title: "Terms of Service | SellerMind",
    description: "Terms of service for SellerMind - Read our terms governing the use of our AI-powered tools.",
    url: "https://thesellermind.com/terms",
    type: "website",
  },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-4xl space-y-8">
      <div className="text-center">
        <h1 className="text-3xl font-bold text-foreground-primary sm:text-4xl">
          Terms of Service
        </h1>
        <p className="mt-2 text-foreground-secondary">
          Last updated: January 2025
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Agreement to Terms</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            By accessing or using SellerMind (&quot;the Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service.
          </p>
          <p className="mt-4">
            <strong>SellerMind is not affiliated with, endorsed by, or connected to Etsy, Inc.</strong> Etsy is a trademark of Etsy, Inc.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Description of Service</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            SellerMind provides AI-powered tools for Etsy sellers, including but not limited to:
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>Listing Generator - Create SEO-optimized product listings</li>
            <li>Auto Reply - Generate customer service responses</li>
            <li>Holiday Marketing - Create seasonal marketing content</li>
            <li>Review Handler - Generate review responses</li>
            <li>Batch Optimizer - Optimize multiple listings at once</li>
          </ul>
          <p className="mt-4">
            We reserve the right to modify, suspend, or discontinue any part of the Service at any time.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>AI-Generated Content Disclaimer</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p className="font-semibold">
            AI-generated content is for reference only. Please review and edit before publishing on your shop.
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>All content generated by our AI tools is for informational purposes only</li>
            <li>You are responsible for reviewing and editing all generated content before use</li>
            <li>We do not guarantee the accuracy, completeness, or suitability of AI-generated content</li>
            <li>You are responsible for ensuring your use of generated content complies with Etsy&apos;s policies</li>
            <li>We are not responsible for any outcomes resulting from the use of AI-generated content</li>
          </ul>
          <p className="mt-4">
            The Service is provided &quot;as is&quot; without warranties of any kind, express or implied.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>User Responsibilities</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>By using the Service, you agree to:</p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>Use the Service only for lawful purposes and in accordance with these Terms</li>
            <li>Not use the Service to generate content that violates any law or regulation</li>
            <li>Not use the Service to infringe on any intellectual property rights</li>
            <li>Not attempt to gain unauthorized access to any part of the Service</li>
            <li>Not interfere with or disrupt the Service or servers connected to the Service</li>
            <li>Comply with all applicable Etsy policies and guidelines when using generated content</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Intellectual Property</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            The Service and its original content, features, and functionality are owned by SellerMind and are protected by international copyright, trademark, and other intellectual property laws.
          </p>
          <p className="mt-4">
            You retain ownership of any content you input into the Service. You grant us a limited license to use your input solely to provide the Service to you.
          </p>
          <p className="mt-4">
            Generated content may be similar to content used by others. We are not responsible for any intellectual property disputes arising from your use of generated content.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Limitation of Liability</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            To the fullest extent permitted by law:
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>SellerMind shall not be liable for any indirect, incidental, special, consequential, or punitive damages</li>
            <li>SellerMind shall not be liable for any loss of profits, data, goodwill, or other intangible losses</li>
            <li>SellerMind shall not be liable for any outcomes resulting from the use of AI-generated content</li>
            <li>SellerMind shall not be liable for any actions taken by Etsy against your shop</li>
            <li>Our total liability shall not exceed $100 USD</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Indemnification</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            You agree to defend, indemnify, and hold harmless SellerMind, its operators, and any affiliated parties from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees arising out of or relating to your use of the Service or violation of these Terms.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Privacy</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            Your privacy is important to us. Please review our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link> to understand how we collect, use, and protect your information.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Third-Party Links</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            The Service may contain links to third-party websites or services that are not owned or controlled by SellerMind. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Service Availability</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            We strive to keep the Service available at all times, but we do not guarantee uninterrupted access. The Service may be temporarily unavailable due to:
          </p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>Scheduled or emergency maintenance</li>
            <li>Technical issues beyond our control</li>
            <li>Third-party service disruptions</li>
            <li>Force majeure events</li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Changes to Terms</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            We reserve the right to modify or replace these Terms at any time at our sole discretion. If a revision is material, we will provide at least 30 days&apos; notice prior to any new terms taking effect.
          </p>
          <p className="mt-4">
            Continued use of the Service after any changes constitutes acceptance of the new Terms.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Governing Law</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which SellerMind operates, without regard to its conflict of law provisions.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Severability</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            If any provision of these Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Entire Agreement</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>
            These Terms, together with our Privacy Policy, constitute the entire agreement between you and SellerMind regarding the Service and supersede all prior agreements and understandings.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Contact Information</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-foreground-secondary">
          <p>If you have any questions about these Terms, please contact us:</p>
          <ul className="list-disc pl-5 space-y-2 mt-4">
            <li>Email: legal@thesellermind.com</li>
            <li>Website: https://thesellermind.com</li>
          </ul>
        </CardContent>
      </Card>

      <div className="flex justify-center">
        <Link
          href="/"
          className="text-primary hover:text-primary-hover font-medium"
        >
          ← Back to Home
        </Link>
      </div>
    </div>
  );
}
